### ISSUE TITLE
is it Free to use?

### ISSUE THREAD

**Issue by pranavlathigara** [bridgefy/bridgefy-android-samples#1]
Hi 
I want use Bridgefy Sdk in my app but i do not See any pricing plan from website so is it free or not ?

**Comment by dustedrob** [comment]
Hi, the Bridgefy SDK has a free plan so you can get started developing with it. The free plan includes 10 users and unlimited messages for one month. Afterwards, you can upgrade to a paid plan or request an extension for the free plan. If you require more information please [contact us](https://www.bridgefy.me/contact.php) .

We'll be adding the pricing and plan information to our website soon.
