### ISSUE TITLE
Unable to send message, missing public key for receiver

### ISSUE THREAD

**Issue by sagarkacha** [bridgefy/bridgefy-android-samples#10]
Sending message from one device to another device gives me unable to send message, missing public key for receiver. Is there any setup or its a issue related to lib? Please guild me if I am wrong.

**Comment by kekoyde** [comment]
Bridgefy SDK works with a one-to-one encryption model, so you need to connect at least once with another bridgefy sdk user, this action is reported in StateListener.onDeviceConnected. 
After knowing the recipient's public key, messages are encrypted and sent.
If you still have a problem, I will keep an eye on it.
Regards
