### ISSUE TITLE
could not resolve com.bridgefy:android-sdk:1.1.24.

### ISSUE THREAD

**Issue by imran-samed** [bridgefy/bridgefy-android-samples#11]
facing issue while adding Bridgefy in gradle

ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.bridgefy:android-sdk:1.1.24.
Show Details
Affected Modules: app

**Comment by kekoyde** [comment]
Thank you for reporting issue, it has been solved, due to improvements in our repository.

**Comment by pankajPizone** [comment]
I'm facing the same issue, @kekoyde how did you solve this please let me know.

**Comment by pankajPizone** [comment]
I'm using npm lib with react native

`https://bitbucket.org/bridgefy/react-native-bridgefy-sdk/src/master/`

**Comment by avinz** [comment]
Also facing same issue:
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.bridgefy:android-sdk:1.1.24.
