### ISSUE TITLE
Start as a background service

### ISSUE THREAD

**Issue by hakansuluoglu** [bridgefy/bridgefy-android-samples#18]
Hi
As far as I understand from examples and the application, SDK receives messages only when the application is running. Is it possible to start Bridgefy as a background service? If it's possible, what are the possible effects on device resources? 

Thanks in advance🤗

**Comment by kekoyde** [comment]
Hi hakansuluoglu, If it is possible that Bridgefy works in the background, the requirements are to start the service in background and keep the Bluetooth antenna on, the SDK is optimized to not consume the battery, the handling of tasks when receiving a message, is the responsibility of the developer.

For iOS development, the framework works in background mode see the doc [here](https://github.com/bridgefy/bridgefy-ios-developer#background-mode).
For Android it requires implementation of Service Background see the doc [here](https://developer.android.com/training/run-background-service/create-service).
