### ISSUE TITLE
How to set the device/user name like in the Bridgefy app?

### ISSUE THREAD

**Issue by vishu103** [bridgefy/bridgefy-android-samples#19]
I want the user to be able to set his/her own name while registering in the app. Right now the getDeviceName on other phones return null. How do I set the user's name.

**Comment by kekoyde** [comment]
Bridgefy does not change the name of the device so the developer can do it however each Bridgefy user has a unique UUID, so it is the differentiator they need, this uuid can be obtained this way:
**Device.getUserId();**
to obtain the UUID of the current device:
**Bridgefy.getInstance().getBridgefyClient().getUserUuid();**
you can relate the UUID to business logic.
