### ISSUE TITLE
How to implement message relay in the SDK?

### ISSUE THREAD

**Issue by vishu103** [bridgefy/bridgefy-android-samples#20]
If A and C are not in range but B is in between them and is in both of their range, How can I implement the message relay between A and C through B in the Android Sdk.

**Comment by kekoyde** [comment]
Sorry for the delay, 
Bridgefy creates mesh networks between devices with our technology, if A and C are connected with B, 
So A and C do not see each other, B is able to transmit messages sent between A and C. 
[You can send messages over the mesh or directly using the following steps.](https://github.com/bridgefy/bridgefy-android-samples#sending-messages-and-receiving-messages)

Bridgefy optimized the forwarding algorithm, decreasing the forwarding time and the time of a message traveling on the mesh network, the [SDK can be configured with different energy and engine profiles](https://github.com/bridgefy/bridgefy-android-samples#configuration-options).
