### ISSUE TITLE
Is it possible to send file or picture without Internet connection?

### ISSUE THREAD

**Issue by YimingLi-1996** [bridgefy/bridgefy-android-samples#22]
Hi! Is it possible to send file or picture without Internet connection? I noticed that in the demo app I can only send location information.

**Comment by kekoyde** [comment]
Yes, Bridgefy can send data only in direct messages, you can use the [Message.Builder](https://bridgefy.me/docs/javadoc/com/bridgefy/sdk/client/Message.Builder.html) class to configure the outgoing message.
**Note:** Bridgefy work with Bluetooth Low Energy, so the bandwidth is limited, the data sent will take time depending on the size, **we recommend you to send data of reasonable size**.
