### ISSUE TITLE
onBroadcastMessageReceived does not include byte array of content from sendBroadcastMessage

### ISSUE THREAD

**Issue by trancee** [bridgefy/bridgefy-android-samples#26]
I am quite new to this library and I am trying to send broadcast a binary payload to all nearby devices.
```
Message.Builder builder = new Message.Builder();
builder.setData(Base64.decode(data, Base64.DEFAULT));
Message message = builder.build();

Bridgefy.sendBroadcastMessage(message);
```
That seems to work and the `Message` does include the binary `data` payload as byte array.

But when I receive that message via `onBroadcastMessageReceived` the `getData()` function returns `null`.

What do I have to do to make this work?

**Comment by kekoyde** [comment]
Sorry for the delay, we are implementing improvements in the Bridgefy algorithm and have a limit on the output of the antenna ble, if the data travels by broadcast or the mesh, it would take significantly more time to be distributed and would cause blocking for other messages. 
So the sending of data is possible in 1:1 messages,  we will continue working to offer better features.
