### ISSUE TITLE
I was hoping you can help me.

### ISSUE THREAD

**Issue by ifmvo** [bridgefy/bridgefy-android-samples#8]
Hello, I know the Bridgefy SDK is based on Bluetooth from https://bridgefy.me/.
Bridgefy is a great project, but I am now looking for an open source project or SDK based on Wi-Fi P2P, and ask if you understand. I watched the WiFi tutorial on the Android website, but I wanted to find a mature, easy-to-use open source project or SDK based on Wi-Fi P2P

**Comment by kekoyde** [comment]
Hi, thanks for trying Bridgefy, sure, bridgefy can help you with connectivity between devices using Bluetooth and Wifi (in our roadmap), you can try the free version for developers, and tell us more about your project, sure we can help.
Regards.
