### ISSUE TITLE
A fatal error has occurred please contact support (code=-66)

### ISSUE THREAD

**Issue by djoks** [bridgefy/bridgefy-android-samples#9]
I keep getting this error when I try the app.  All my other colleagues are getting the same error.

**Comment by mcdull** [comment]
Same error.

**Comment by etnperlong** [comment]
Same error.

**Comment by x9b8** [comment]
Same here on Android 8! Any solutions?

**Comment by x9b8** [comment]
And also on Android 9!

Works Perfect with iPhone, online and also offline!

**Comment by kekoyde** [comment]
Thanks to everyone for reporting the issue, we had a period of improvements in our services, so we updated our versions,
Bridgefy Android SDK current version: 1.1.24
Bridgefy iOS SDK current version: 0.1.33
We apologize for any inconvenience this may have caused,
I'll be watching what happens.
Regards.
